---
# Copyright (C) 2024 Maxwell G <maxwell@gtmx.me>
# SPDX-License-Identifier: MIT

default:
  image: "registry.fedoraproject.org/fedora:latest"
  before_script:
    - >-
      sudo dnf install
      --setopt=install_weak_deps=0 -y
      askalono-cli
      git-core
      nox
      python3.9
      python3.10-devel
      python3.11-devel
      python3.12-devel

test:
  script:
    - "nox -e test"

formatters:
  script:
    - "nox -e formatters -- --check"

codeqa:
  script:
    - "nox -e codeqa"

build-srpms:
  before_script:
    - |-
      if [ -n "$(rpm -E '%{?rhel}')" ]; then
        dnf install -y sudo
        sudo dnf install --setopt=install_weak_deps=0 -y cargo
        sudo dnf install -y epel-release
        crb enable
        cargo install askalono-cli
        sudo cp ~/.cargo/bin/askalono /usr/bin/askalono
        sudo chmod a+x /usr/bin/askalono
      else
        sudo dnf install --setopt=install_weak_deps=0 -y askalono-cli
      fi
    - >-
      sudo dnf install
      --setopt=install_weak_deps=0 -y
      golang-bin
      git-core
      packit
      pipx
      rpmdevtools
  script:
    - packit srpm -p go-vendor-tools
    - packit srpm -p autorestic
    - packit srpm -p fzf
  image: "$IMAGE"
  parallel:
    matrix:
      - IMAGE:
          - "registry.fedoraproject.org/fedora:rawhide"
          - "registry.fedoraproject.org/fedora:40"
          - "registry.fedoraproject.org/fedora:39"
          - "registry.fedoraproject.org/fedora:38"
          - "quay.io/centos/centos:stream9"
