# Copyright (C) 2024 Maxwell G <maxwell@gtmx.me>
# SPDX-License-Identifier: MIT

upstream_package_name: go-vendor-tools
srpm_build_deps:
  - golang-bin
  - git-core
  - pipx
  - rpmdevtools
  - /usr/bin/unshare
# This messes up wait-for-copr, since each merge commit has a different commit
# hash and then fclogr calculates a different NVR than what the actual package
# built.
merge_pr_in_ci: false
packages:
  # Main package
  go-vendor-tools:
    specfile_path: go-vendor-tools.spec
    actions:
      fix-spec-file:
        - "./contrib/main-archive.sh go-vendor-tools.spec"
      create-archive:
        - "./contrib/main-archive.sh go-vendor-tools.spec"
        - "sh -c 'ls go-vendor-tools-*.tar.gz'"
    release_suffix: ""
    osh_diff_scan_after_copr_build: false
  # Integration packages
  autorestic:
    specfile_path: autorestic.spec
    paths:
      - ./tests/integration/autorestic
    actions:
      fix-spec-file: []
      create-archive:
        - bash -x ../../../contrib/integration-archive.sh
      post-upstream-clone:
        - bash -x ../../../contrib/wait-for-copr.sh
    osh_diff_scan_after_copr_build: false
  fzf:
    specfile_path: fzf.spec
    paths:
      - ./tests/integration/fzf
    actions:
      fix-spec-file: []
      create-archive:
        - bash -x ../../../contrib/integration-archive.sh
      post-upstream-clone:
        - bash -x ../../../contrib/wait-for-copr.sh
    osh_diff_scan_after_copr_build: false
jobs:
  - job: copr_build
    packages:
      - go-vendor-tools
      # - autorestic
      # - fzf
    targets:
      fedora-all-x86_64:
        # Extra dependencies (trivy, python-zstarfile) not packaged in Fedora
        additional_repos:
          - "copr://@go-sig/go-vendor-tools-dev"
      epel-9-x86_64:
        # Extra dependencies (trivy, python-zstarfile) not packaged in Fedora
        additional_repos:
          - "copr://@go-sig/go-vendor-tools-dev"
      epel-10-x86_64:
        # Extra dependencies (trivy, python-zstarfile) not packaged in Fedora
        additional_repos:
          - "copr://@go-sig/go-vendor-tools-dev"
    trigger: pull_request

  - job: tests
    trigger: pull_request
    skip_build: true
    tmt_plan: "/plans/pypi-test"
    identifier: pypi-test
    # TODO(gotmax23): Is this something we actually want?
    # The initial motivation was to make it possible to make changes to
    # go-vendor-tools and go-rpm-macros at the same time
    tf_extra_params: &tf_extra_params
      environments:
        - tmt:
          extra_args:
            prepare:
              - --insert
              - -h
              - install
              - --copr
              - '@go-sig/go-vendor-tools-dev'
              - --order
              - '35'
    # We can get away only running pypi-test on Rawhide and EL.
    # We run rpm-test everywhere; it's the same checks, just one with PyPI deps
    # and the other with RPM deps.
    targets: &tf_targets_pypi_test
      fedora-rawhide-x86_64: {}
      epel-9-x86_64:
        distros:
          - centos-stream-9
      epel-10-x86_64:
        distros:
          - centos-stream-10
    # Even though we're running with skip_build, not specifying packages causes this to run
    # three times for each target.
    packages:
      - go-vendor-tools

  - job: tests
    trigger: pull_request
    tmt_plan: "/plans/rpm-test"
    identifier: rpm-test
    tf_extra_params: *tf_extra_params
    packages:
      - go-vendor-tools
    targets: &tf_targets_rpm_test
      fedora-all-x86_64: {}
      epel-9-x86_64:
        distros:
          - centos-stream-9
      epel-10-x86_64:
        distros:
          - centos-stream-10

  - job: copr_build
    packages:
      - go-vendor-tools
      - autorestic
      - fzf
    targets:
      - fedora-all-x86_64
      - fedora-all-x86_64
      - epel-10-aarch64
      - epel-10-x86_64
      - epel-9-aarch64
      - epel-9-x86_64
    owner: "@go-sig"
    project: go-vendor-tools-dev
    trigger: commit
    branch: main
      - go-vendor-tools

  - job: tests
    trigger: commit
    branch: main
    skip_build: true
    tmt_plan: "/plans/pypi-test"
    identifier: pypi-test
    tf_extra_params: *tf_extra_params
    targets: *tf_targets_pypi_test

  - job: tests
    trigger: commit
    branch: main
    tmt_plan: "/plans/rpm-test"
    identifier: rpm-test
    tf_extra_params: *tf_extra_params
    packages:
      - go-vendor-tools
    targets: *tf_targets_rpm_test
