# Copyright (C) 2024 Maxwell G <maxwell@gtmx.me>
# SPDX-License-Identifier: MIT

# Generated by go2rpm 1.10.0
# https://github.com/junegunn/fzf
%global goipath         github.com/junegunn/fzf
Version:                0.46.1
%global tag             %{version}

%gometa -L -f

%global common_description %{expand:
:cherry_blossom: A command-line fuzzy finder.}

Name:           fzf
Release:        1%{?dist}
Summary:        :cherry_blossom: A command-line fuzzy finder

SourceLicense:  MIT
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
Source1:        fzf-%{version}-vendor.tar.xz

BuildRequires:  go-vendor-tools

%description %{common_description}

%prep
%autosetup -p1 -b1
%goprep -ke

%build
%dnl We don't care about building or installing the package for the purposes of
%dnl the integration test.
%dnl %gobuild -o fzf %{goipath}
%global debug_package %{nil}

%install
%go_vendor_license_install

%check
%go_vendor_license_check

%files -f licenses.list
%doc doc ADVANCED.md BUILD.md CHANGELOG.md README-VIM.md README.md

%changelog
* Thu Feb 29 2024 Maxwell G <maxwell@gtmx.me> - 0.46.1-1
- Initial package
